config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new]
  resources :properties do
    get '/bookings/dates', to: 'bookings#dates'
    resources :bookings, only: [:create, :update]
  end

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  scope :dashboard do
    get '/', to: 'users#dashboard'
    get 'my_properties', to: 'properties#my_properties'
    get 'my_bookings', to: 'bookings#my_bookings'
  end

  root 'properties#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :property
  belongs_to :user

  enum status: [:pending, :confirmed, :cancelled]
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy

  enum property_type: [:none_selected, :shared_room, :private_room, :entire_unit]

  mount_uploader :image, ImageUploader
  validates_processing_of :image
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :properties, dependent: :destroy
  has_many :bookings 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  include SessionsHelper
  include PropertiesHelper

  def index
    if Property.find(params[:property_id]) && is_owner?(current_user.id)
      @bookings = Property.find(params[:property_id]).bookings
    else
    end
  end

  def my_bookings
    if logged_in?
      @bookings = Booking.where(user_id: current_user.id)
    else
      redirect_to 'login'
    end
  end

  def dates
    @bookings = Property.find(params[:property_id]).bookings

    @dates = [];
    @bookings.each do |booking|
      @dates.concat((booking.start_date..booking.end_date).to_a)
    end

    render json: @dates
  end

  def create

    if !logged_in?
      redirect_to '/login'
    end

    if !is_owner?(params[:property_id])
      booking = Booking.new(booking_params)
      booking.start_date = Date.strptime(booking_params[:start_date], '%m-%d-%Y')
      booking.end_date = Date.strptime(booking_params[:end_date], '%m-%d-%Y')
      booking.user_id = current_user.id
      booking.property_id = params[:property_id]
      booking.status = 1
      
      if booking.save()
        redirect_to '/dashboard/my_bookings'
      end
    else
    end
  end

  def thank_you
  end

  def update
    booking = Booking.find(params[:id])
    is_owner = is_owner?(params[:property_id])
    is_booked_user  = current_user.id == booking.user_id
    
    if (is_owner ||  is_booked_user)
      booking.update(booking_params)
    end
    if is_owner
      redirect_to '/dashboard/my_properties'
    elsif is_booked_user
      redirect_to '/dashboard/my_bookings'
    end
  end

  private
  def booking_params
    params.require(:booking).permit([:property_id, :user_id, :start_date, :end_date, :status])
  end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  include SessionsHelper

  def index
    @properties = Property.all
  end

  def my_properties
    @properties = Property.where(user_id: current_user.id)
    render 'index'
  end

  def new
    if !logged_in?
      redirect_to 'login'
    end

    @property = Property.new()
    @property_types = Property.property_types
  end

  def create
    if !logged_in?
      redirect_to 'login'
    end

    property = Property.new(property_params)
    property.user_id = current_user.id

    if property.save
      redirect_to '/'
    else
      render 'new'
    end
  end

  def show
    @property = Property.find(params[:id])
    @booking = Booking.new()
  end

  def edit
    @property = Property.find(params[:id])
    @property_types = Property.property_types
  end

  def destroy
    @property = Property.find(params[:id])
    @property.destroy

    redirect_to '/'
  end

  def update
    @property = Property.find(params[:id])
    
    if @property.update(property_params)
      redirect_to property_url
    else
      redirect_to '/'
    end
  end

  private

  def property_params()
    permitted_fields = [:price, :name, :property_type, :address, :city, :state, :country, :capacity, :image, :booking_id, :user_id]
    params.require(:property).permit(permitted_fields)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      session[:user_id] = user.id
      redirect_to '/'
    else
      # Create an error message.
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    # log_out
    session.delete(:user_id)
    @current_user = nil
    redirect_to login_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in(@user)
        format.html { redirect_to '/dashboard/', notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper

end

app/helpers/properties_helper.rb
module PropertiesHelper
  include SessionsHelper

  def is_owner?(id)
    if current_user == Property.find(id).user
      return true
    else
      return false
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/index.html.erb
<% @bookings.each do |booking| %>


<% end %>

app/views/bookings/my_bookings.html.erb
<% @bookings.each do |booking| %>
  <h1><%= booking.property.name %></h1>
  <p><%= booking.start_date %> to <%= booking.end_date %></p>
  <p>Status: <%= booking.status.humanize %>

  <% if booking.status != 'cancelled' %>
    <div>
      <%= link_to "Edit Booking", [booking.property, booking] %>
      <%= form_for [booking.property, booking] do |f| %>
        <%= f.hidden_field :status, value: 'cancelled' %>
        <%= f.submit "Cancel Booking"%>
      <% end %>
    </div>
  <% end %>

<% end %>
  

app/views/bookings/thank_you.html.erb
<h1> Thank you for booking</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BedNBlockchain</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h1><%= link_to "BedNBlockchain", root_path %></h1>
        </div>


        <div class="col-md-6">
          <% if logged_in? %>

            <a href="/dashboard">My Dashboard</a>
          <% else %>
            <%= link_to "Login", login_path %>
          <% end %>
        </div>
      </div>

    <%= yield %>
    </div>
  </body>
</html>

app/views/properties/edit.html.erb
<h1> Edit Property</h1>
<%= form_for @property do |form| %>

  <%= form.label :name %>
  <%= form.text_field :name %><br>

  <%= form.label :property_type %>
  <%= form.select :property_type, options_for_select(@property_types.collect { |h| [h[0].humanize, h[0]] }, selected: @property.property_type), {} %><br>

  <%= form.label :capacity %>
  <%= form.number_field :capacity %><br>

  <%= form.label :price %>
  <%= form.number_field :price %><br>

  <%= form.label :address %>
  <%= form.text_field :address %><br>

  <%= form.label :city %>
  <%= form.text_field :city %><br>

  <%= form.label :state %>
  <%= form.text_field :state %><br>

  <%= form.label :country %>
  <%= form.text_field :country %><br>

  <%= form.label :image %>
  <%= form.file_field :image %><br>

  <%= submit_tag("Submit") %>
  <%= link_to 'Destroy', property_path(@property), method: :delete %>
<% end %>

app/views/properties/index.html.erb
<% @properties.each do |property| %>

<div class="row">
  <div class="col-sm-2">
    <% if property.image.thumb.url %>
      <%= image_tag(property.image.thumb.url, class: "property-image") %>
    <% end %>
  </div>
  <div class="col-sm-6">
    <%= link_to(property) do %>
      <h1 class="property-name"><%= property.name %></h1>
    <% end %>
    <p class="property-details"><%= property.property_type.humanize %> - Sleeps <%= property.capacity %>
    <br><%= property.address %> <%= property.city %></p>
  </div>
  <div class="col-sm-4">
    <h1 class="property-price">$ <%= property.price %></h1>
    <p class="per-night">per night</p>
  </div>
</div>
<% end %>

<% link_to @properties %>

app/views/properties/new.html.erb
<%= form_for @property do |form| %>

  <%= form.label :name %>
  <%= form.text_field :name %><br>

  <%= form.label :property_type %>
  <%= form.select :property_type, options_for_select(@property_types.collect { |h| [h[0].humanize, h[0]] }, selected: @property.property_type), {} %><br>

  <%= form.label :capacity %>
  <%= form.number_field :capacity %><br>

  <%= form.label :price %>
  <%= form.number_field :price %><br>

  <%= form.label :address %>
  <%= form.text_field :address %><br>

  <%= form.label :city %>
  <%= form.text_field :city %><br>

  <%= form.label :state %>
  <%= form.text_field :state %><br>

  <%= form.label :country %>
  <%= form.text_field :country %><br>

  <%= form.label :image %>
  <%= form.file_field :image %><br>

  <%= submit_tag("Submit") %>
<% end %>

app/views/properties/show.html.erb
<div class="row">
  <div class="col-sm-2">
    <% if @property.image.thumb.url %>
      <%= image_tag(@property.image.thumb.url, class: "property-image") %>
    <% end %>
  </div>
  <div class="col-sm-6">
    <%= link_to(@property) do %>
      <h1 class="property-name"><%= @property.name %></h1>
    <% end %>
    <p class="property-details"><%= @property.property_type.humanize %> - Sleeps <%= @property.capacity %>
    <br><%= @property.address %> <%= @property.city %></p>
  </div>
  <div class="col-sm-4">
    <h1 class="property-price">$ <%= @property.price %></h1>
    <p class="per-night">per night</p>
  </div>
</div>

<% if @property.user_id != current_user.id %>
  <%= form_for [@property, @booking] do |f| %>
    <div>
      <%= f.label :start_date %> *<br>
      <%= f.text_field :start_date, required: true, id: "start_date_datepicker" %>
    </div>
    <div>
      <%= f.label :end_date %> *<br>
      <%= f.text_field :end_date, required: true, id: "end_date_datepicker" %>
    </div>

    <%= f.submit "Make Booking"%>
  <% end %>
<% else %>
  <%= link_to "Edit Property", edit_property_path %>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= form.label :email %>
  <%= form.text_field :email %><br>

  <%= form.label :password %>
  <%= form.text_field :password %><br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/dashboard.html.erb
<h3><a href="/dashboard/my_properties">My Properties</a></h3>
<h3><%= link_to "List a Property", new_property_path%></h3>
<h3><a href="/dashboard/my_bookings">My Bookings</a></h3>
<h3><%= link_to "Log out", logout_path, method: :delete %></h3>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1> <%= @user.email %> </h1>
<button>
<%= link_to "Log out", logout_path, method: :delete %>
</button>